server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://114.55.30.247:3306/reptile?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: LJRoOrnaWtG0
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
          max-lifetime: 1765000
          maximum-pool-size: 15
  thymeleaf:
    cache: false
    


    
  